using EtikKurul.Infrastructure.Enums;

namespace EtikKurul.Modules.Applications.Models;

public sealed record ApplicationChecklistItemResult(
    Guid ChecklistItemId,
    string ItemCode,
    string Label,
    ApplicationChecklistSeverity Severity,
    ApplicationChecklistStatus Status,
    string Message,
    bool AutoGenerated,
    DateTimeOffset? ResolvedAt);
