using EtikKurul.Infrastructure.Enums;

namespace EtikKurul.Infrastructure.Entities;

public class ApplicationChecklist
{
    public Guid Id { get; set; }
    public Guid ApplicationId { get; set; }
    public string ItemCode { get; set; } = string.Empty;
    public string Label { get; set; } = string.Empty;
    public ApplicationChecklistSeverity Severity { get; set; }
    public ApplicationChecklistStatus Status { get; set; }
    public string Message { get; set; } = string.Empty;
    public bool AutoGenerated { get; set; }
    public DateTimeOffset? ResolvedAt { get; set; }
    public Application Application { get; set; } = null!;
}
