using EtikKurul.Infrastructure.Enums;

namespace EtikKurul.Api.Contracts.Applications;

public sealed record ApplicationChecklistItemResponse(
    Guid ChecklistItemId,
    string ItemCode,
    string Label,
    ApplicationChecklistSeverity Severity,
    ApplicationChecklistStatus Status,
    string Message,
    bool AutoGenerated,
    DateTimeOffset? ResolvedAt);
